# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Angelos Zagouris
title: Help Desk Analyst
email: p13zago@inio.gr
cv   : "AggelosZagourisCV0.pdf"
#website: Your website (eg. https://google.com)(optional)

# Social links
github_username:  AggZag
#facebook_username: AggelosZagouris
#instagram_username: https://www.instagram.com/aggeloszagouris/
#linkedin_username: Aggelos-Zagouris

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Dealing with hardware and software problems from fourteen years old.Ready to assess the problem and actively deal with it as fast as possible.Comfortable working in a team ready to give and learn from it.Always working with responsibility toward the company and being ecient with the task at hand.Actively organizing the tasks tha need to be done and solve them with order.
  Down Below there is a link for my resume
    - [My Awesome Resume](https://github.com/AggZAG/AggZAG.github.io/blob/main/docs/AggelosZagourisCV0.pdf)
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I am a team work person,and very capable working in a fast paced environment .

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

theme: jekyll-theme-time-machine